List<Map<String, dynamic>> getWorkoutsByCategoryAndLevel(String category, String level) {
  if (category == 'Abs') {
    return [
      {
        'name': 'Jumping Jacks',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/jumping_jacks.gif',
        'instructions': 'Start with your feet together and your arms by your sides, then jump up with your feet apart and your hands overhead',
      },
      {
        'name': 'Abdominal Crunches',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/abdominal_crunches.gif',
        'instructions': 'Lie on your back with your knees bent and your arms stretched forward',
      },
      {
        'name': 'Russian Twist',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/russian_twist.gif',
        'instructions' : 'Sit on the floor with your knees bent, feet lifted a little bit and back tilted backwards. Then hold your hands together and twist from side to side',
      },
      {
        'name': 'Mountain Climber',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/mountain_climber.gif',
        'instructions' : 'Start in the push-up position. Bend your right knee towards your chest and keep your left leg straight, then quickly switch one leg to the other',
      },
      {
        'name': 'Heel Touch',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/heel_touch.gif',
        'instructions' : 'Lie on the ground with your legs bent and your arms by your sides. Slightly lift your upper body off the floor and make your hands alternately reach your heels',
      },
      {
        'name': 'Leg Raises',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/leg_raises.gif',
        'instructions' : 'Lie down on your back, and put your hands beneath your hips for support. Then lift your leg up until they form a right angle with the floor',
      },
      {
        'name': 'Cobra Stretch',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/cobra_stretch.gif',
        'instructions' : 'Lie down on your stomach and bend your elbows with your hands beneath your shoulders.',
      },
      {
        'name': 'Abdominal Crunches',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/abdominal_crunches.gif',
        'instructions': 'Lie on your back with your knees bent and your arms stretched forward',
      },
      {
        'name': 'Russian Twist',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/russian_twist.gif',
        'instructions' : 'Sit on the floor with your knees bent, feet lifted a little bit and back tilted backwards. Then hold your hands together and twist from side to side',
      },
      {
        'name': 'Mountain Climber',
        'reps': level == 'Beginner' ? 10 : level == 'Intermediate' ? 15 : 20,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/mountain_climber.gif',
        'instructions' : 'Start in the push-up position. Bend your right knee towards your chest and keep your left leg straight, then quickly switch one leg to the other',
      },
    ];
  } else if (category == 'Arms') {
    return [
      {
        'name': 'Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/arm_raises.gif',
        'instructions' : 'Stand on the floor with your arms extended straight forward at your shoulder height.',
      },
      {
        'name': 'Side Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/side_arms.gif',
        'instructions' : 'Stand with your feet and shoulder width apart. Raise your arms to the sides at shoulder height, then put them down.',
      },
      {
        'name': 'Triceps Dips',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/triceps_dips.gif',
        'instructions' : 'For the start position, sit on the chair. Then move your hip off the chair with your hands holding the edge of the chair.',
      },
      {
        'name': 'Diamond Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/diamond.gif',
        'instructions' : 'Start in the push-up position. Make a diamond hape with your forefingers and thumbs together under your chest.',
      },
      {
        'name': 'Jumping Jacks',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/jumping_jacks.gif',
        'instructions': 'Start with your feet together and your arms by your sides, then jump up with your feet apart and your hands overhead',
      },
      {
        'name': 'Wall Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/wall_pushups.gif',
        'instructions' : 'Stand in front of a wall one big step away from it. Then put your hands out straight towards the wall and lean against it. Lift your heels.',
      },
      {
        'name': 'Inch Worms',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/inchworms.gif',
        'instructions' : 'Bend your body and walk your hands in front of your as far as you can, then walk your hands back. Repeat the exercise.',
      },
      {
        'name': 'Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/arm_raises.gif',
        'instructions' : 'Stand on the floor with your arms extended straight forward at your shoulder height.',
      },
      {
        'name': 'Side Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/side_arms.gif',
        'instructions' : 'Stand with your feet and shoulder width apart. Raise your arms to the sides at shoulder height, then put them down.',
      },
      {
        'name': 'Triceps Dips',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/triceps_dips.gif',
        'instructions' : 'For the start position, sit on the chair. Then move your hip off the chair with your hands holding the edge of the chair.',
      },
    ];
  } else if (category == 'Chest') {
    return [
      {
        'name': 'Jumping Jacks',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/jumping_jacks.gif',
        'instructions': 'Start with your feet together and your arms by your sides, then jump up with your feet apart and your hands overhead',
      },
      {
        'name': 'Incline Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/incline.gif',
        'instructions' : 'Start in the regular push-up position but with your hands elevated on a chair or bench. Remember to keep your body straight.',
      },
      {
        'name': 'Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/push-ups.gif',
        'instructions' : 'Keep your body straight while raising and lowering your body with your arms.',
      },
      {
        'name': 'Wide Arms Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/wide_arm.gif',
        'instructions' : 'Start with regular push-up position but with your hands spread wider than your shoulders',
      },
      {
        'name': 'Triceps Dips',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/triceps_dips.gif',
        'instructions' : 'For the start position, sit on the chair. Then move your hip off the chair with your hands holding the edge of the chair.',
      },
      {
        'name': 'Cobra Stretch',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/cobra_stretch.gif',
        'instructions' : 'Lie down on your stomach and bend your elbows with your hands beneath your shoulders.',
      },
      {
        'name': 'Incline Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/incline.gif',
        'instructions' : 'Start in the regular push-up position but with your hands elevated on a chair or bench. Remember to keep your body straight.',
      },
      {
        'name': 'Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/push-ups.gif',
        'instructions' : 'Keep your body straight while raising and lowering your body with your arms.',
      },
      {
        'name': 'Wide Arms Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/wide_arm.gif',
        'instructions' : 'Start with regular push-up position but with your hands spread wider than your shoulders',
      },
      {
        'name': 'Triceps Dips',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/triceps_dips.gif',
        'instructions' : 'For the start position, sit on the chair. Then move your hip off the chair with your hands holding the edge of the chair.',
      },
      {
        'name': 'Cobra Stretch',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/cobra_stretch.gif',
        'instructions' : 'Lie down on your stomach and bend your elbows with your hands beneath your shoulders.',
      },
    ];
  } else if (category == 'Back') {
    return [
      {
        'name': 'Jumping Jacks',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/jumping_jacks.gif',
        'instructions': 'Start with your feet together and your arms by your sides, then jump up with your feet apart and your hands overhead',
      },
      {
        'name': 'Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/arm_raises.gif',
        'instructions' : 'Stand on the floor with your arms extended straight forward at your shoulder height.',
      },
      {
        'name': 'Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/push-ups.gif',
        'instructions' : 'Keep your body straight while raising and lowering your body with your arms.',
      },
      {
        'name': 'Rhomboid Pulls',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/rhomboid_pulls.gif',
        'instructions' : 'Raise your arms parallel to the ground, and bend your elbows. Pull your elbows back and squeeze your shoulder blades.',
      },
      {
        'name': 'Side Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/side_arms.gif',
        'instructions' : 'Stand with your feet and shoulder width apart. Raise your arms to the sides at shoulder height, then put them down.',
      },
      {
        'name': 'Prone Triceps Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/prone_pushups.gif',
        'instructions' : 'Slightly raise your chest up, and then go back to the start position.',
      },
      {
        'name': 'Reclined Rhomboid Squeezes',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/reclined_rhomboid_squeezes.gif',
        'instructions' : 'Stretch your arms in front of you, then pull your elbows back to make your elbows at a 90 degree angle and squeeze your shoulder blades.',
      },
            {
        'name': 'Arm Raises',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/arm_raises.gif',
        'instructions' : 'Stand on the floor with your arms extended straight forward at your shoulder height.',
      },
      {
        'name': 'Push-Ups',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/push-ups.gif',
        'instructions' : 'Keep your body straight while raising and lowering your body with your arms.',
      },
      {
        'name': 'Rhomboid Pulls',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/rhomboid_pulls.gif',
        'instructions' : 'Raise your arms parallel to the ground, and bend your elbows. Pull your elbows back and squeeze your shoulder blades.',
      },
    ];
  } else if (category == 'Legs') {
    return [
      {
        'name': 'Side Hop',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/side_hop.gif',
        'instructions' : 'Stand on the floor, put your hands in front of you and hop from side to side.',
      },
      {
        'name': 'Squarts',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/squarts.gif',
        'instructions' : 'Stand with your feet shoulder width apart and your arms stretched forward, then lower your body until your thights are parallel with the floor.',
      },
      {
        'name': 'Side-Lying Leg Lift Left',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/left_side_lying.gif',
        'instructions' : 'Lie down on your side with your head rested on your right arm. Lift your upper leg up and return to the start position',
      },
      {
        'name': 'Side-Lying Leg Lift Right',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/right_side_lying.gif',
        'instructions' : 'Lie down on your side with your head rested on your right arm. Lift your upper leg up and return to the start position',
      },
      {
        'name': 'Backward Lunge',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/backwards_lunge.gif',
        'instructions' : 'Step a big step backward with your right leg and lower your body until your left thigh is parallel to the floor. Return and repeat with the other side.',
      },
      {
        'name': 'Side Hop',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/side_hop.gif',
        'instructions' : 'Stand on the floor, put your hands in front of you and hop from side to side.',
      },
      {
        'name': 'Squarts',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/squarts.gif',
        'instructions' : 'Stand with your feet shoulder width apart and your arms stretched forward, then lower your body until your thights are parallel with the floor.',
      },
      {
        'name': 'Side-Lying Leg Lift Left',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/left_side_lying.gif',
        'instructions' : 'Lie down on your side with your head rested on your right arm. Lift your upper leg up and return to the start position',
      },
      {
        'name': 'Side-Lying Leg Lift Right',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/right_side_lying.gif',
        'instructions' : 'Lie down on your side with your head rested on your right arm. Lift your upper leg up and return to the start position',
      },
      {
        'name': 'Backward Lunge',
        'reps': level == 'Beginner' ? 15 : level == 'Intermediate' ? 20 : 30,
        'sets': level == 'Beginner' ? 2 : level == 'Intermediate' ? 3 : 4,
        'image': 'assets/images/backwards_lunge.gif',
        'instructions' : 'Step a big step backward with your right leg and lower your body until your left thigh is parallel to the floor. Return and repeat with the other side.',
      },
    ];
  }
  // Add more categories
  return [];
}
